INSERT INTO gd_lores (id) VALUES 
('CLS_SAG')
,('CLS_WAR')
,('CLS_ROG')
,('CLS_BAR')
,('CLS_PRI')
,('CLS_PAT')
,('LOC_GMDUNG')
,('AET_COEF_WEAP')
,('AET_COEF_LVL')
,('AET_COEF_AGI')
;
INSERT INTO gd_lores (id) VALUES 
('AET_COEF_STR')
,('AET_COEF_INT')
,('AET_COEF_MAXHP')
,('AET_COEF_CURHP')
,('AET_DMG')
,('AET_HEAL')
,('AET_DURAT')
,('AET_MOV_AMP')
,('AET_STUN')
,('AET_DISOR')
;
INSERT INTO gd_lores (id) VALUES 
('AET_TAR_ALLY')
,('AET_TAR_FOE')
,('AET_AOE')
,('AET_IMMU')
,('AET_RESI')
,('AET_DISP')
,('AET_INVI')
,('ABA_PHYS')
,('ABA_DRUG')
,('ABA_ACID')
;
INSERT INTO gd_lores (id) VALUES 
('ABA_ELEC')
,('ABA_FIRE')
,('ABA_GAS')
,('ABA_INSP')
,('ABA_SOUND')
,('ABA_VVV')
,('ABI_STRIKE')
,('RAT_CRC')
,('RAT_CRD')
,('RAT_MCRC')
;
INSERT INTO gd_lores (id) VALUES 
('RAT_MCRD')
,('RAT_DOD')
,('RAT_END')
,('RAT_WIL')
,('STT_AGI')
,('STT_CHA')
,('STT_STR')
,('STT_INT')
,('STT_CON')
,('STT_INI')
;
INSERT INTO gd_lores (id) VALUES 
('STT_SPE')
,('STT_LUC')
,('STT_TEN')
,('STT_STA')
;