#!/bin/bash

dir=$(dirname $(readlink -f $0))

export PATH="$dir/local/bin:$PATH"

export PERL5LIB="$dir/local/lib/perl5:$PERL5LIB"
export PERL5LIB="$dir/Game-Common/lib:$PERL5LIB"
export PERL5LIB="$dir/Game-Worker/lib:$PERL5LIB"
export PERL5LIB="$dir/Game-Lore/lib:$PERL5LIB"
export PERL5LIB="$dir/Game-Schema/lib:$PERL5LIB"
export PERL5LIB="$dir/Game-Repository/lib:$PERL5LIB"

if [ "$1" == "test" ]; then
	tests="Game-Common/t Game-Worker/t Game-Lore/t Game-Schema/t Game-Repository/t"
	if [ "$2" != "unit" ]; then
		tests="$tests t"
	fi
	prove -l $tests
elif [ "$1" == "tools" ]; then
	cpanm Perl::Tidy Code::TidyAll Perl::Critic
	mkdir -p .git/hooks
	cp script/git-hook-precommit .git/hooks/pre-commit
elif [ "$1" == "lint" ]; then
	tidyall -a --mode lint
elif [ "$1" == "critic" ]; then
	tidyall -a --mode critic
else
	script/server minion worker &
	script/server daemon -l http://*:3001 &
	morbo script/web -w lib templates Game-Common/lib Game-Worker/lib Game-Lore/lib Game-Schema/lib Game-Repository/lib
fi
