#!/bin/bash

dir=$(dirname $(readlink -f $0))

export PATH="$dir/local/bin:$PATH"

export PERL5LIB="$dir/local/lib/perl5:$PERL5LIB"
export PERL5LIB="$dir/Game-Common/lib:$PERL5LIB"
export PERL5LIB="$dir/Game-Worker/lib:$PERL5LIB"

if [ "$1" == "test" ]; then
	prove -l t Game-Common/t Game-Worker/t
else
	script/server minion worker &
	script/server daemon -l http://*:3001 &
	morbo script/web -w lib templates Game-Common/lib Game-Worker/lib
fi
