#!/usr/bin/env perl

use v5.42;

my ($arg) = @ARGV;
$arg //= '';

my $flags = '';
if ($ENV{DEBUG}) {
	say 'Running in debug mode';
	$flags = '-MCarp::Always';
}

if ($arg eq 'lint') {
	system('tidyall -a --mode lint');
}
elsif ($arg =~ /^critic/) {
	system('tidyall -a --mode ' . $arg);
}
elsif ($arg eq 'web') {
	system('pagi-server script/web --host 0.0.0.0');
}
else {
	system("perl $flags script/worker &");
	system("perl $flags script/server");
}

