#!/usr/bin/env perl

use v5.36;

use File::Basename;
use Env qw(@PATH $MOJO_REACTOR);

my $dir = dirname(__FILE__);

unshift @PATH, "$dir/local/bin";
$MOJO_REACTOR = 'My::Mojo::Reactor::UV';

my ($arg) = @ARGV;
$arg //= '';

if ($arg eq 'lint') {
	system('tidyall -a --mode lint');
}
elsif ($arg =~ /^critic/) {
	system('tidyall -a --mode ' . $arg);
}
elsif ($arg eq 'web') {
	system('hypnotoad script/web');
}
elsif ($arg eq 'web-dev') {
	my @watched = qw(lib-base lib templates);
	system("morbo script/web -w @watched");
}
else {
	system('script/worker &');
	system('script/server');
}

