#!/usr/bin/env perl

use v5.38;

use App::Yath::Util qw/find_yath/;

use Env qw(@PERL5LIB $MOJO_REACTOR);
unshift @PERL5LIB, "local/lib/perl5";
$MOJO_REACTOR = 'My::Mojo::Reactor::UV';

exec($^X, find_yath(), @ARGV);

