SEARCH_DIR("/usr/lib/")
SEARCH_DIR("/usr/local/lib/")
SEARCH_DIR("/usr/local/lib/qt5/")
SEARCH_DIR("/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/")
SEARCH_DIR("/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/")
SEARCH_DIR("/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/")
SEARCH_DIR("/usr/local/share/lazarus-2.0.12/packager/units/x86_64-freebsd/")
SEARCH_DIR("./")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/odbc/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/zlib/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/paszlib/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/oggvorbis/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/chm/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-fpcunit/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fpmkunit/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-registry/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl-generics/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/opengl/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fppkg/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/ibase/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-xml/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/hash/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/openal/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl-objpas/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/mysql/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-base/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-db/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-json/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/numlib/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-process/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/postgres/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-net/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/x11/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/dblib/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/cairo/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/regexpr/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/libtar/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/gtk2/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/sqlite/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-res/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl-extra/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-web/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/iconvenc/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/utils-pas2js/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/oracle/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/openssl/")
SEARCH_DIR("/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/")
SEARCH_DIR("/usr/local/bin/")
INPUT(
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/cprt0.o
/usr/lib/crti.o
/usr/lib/crtbeginS.o
/usr/home/bartosz/dox/game-project-01/tools/map-editor/lib/x86_64-freebsd/mapeditor.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/system.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/lnfodwrf.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/exeinfo.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/strings.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/fpintres.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/objpas.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/interfaces.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/forms.o
/usr/home/bartosz/dox/game-project-01/tools/map-editor/lib/x86_64-freebsd/editor.o
/usr/home/bartosz/dox/game-project-01/tools/map-editor/lib/x86_64-freebsd/markerdialog.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/cwstring.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/interfacebase.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/baseunix.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/ctypes.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/unix.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/unixtype.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/initc.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/dynlibs.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/unixcp.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/sysctl.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/unixutil.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/dl.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/types.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/classes.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/sysutils.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/math.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/fpimage.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/lazutf8.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/integerlist.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/lcltype.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/lclproc.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/lmessages.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/lclplatformdef.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/graphtype.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/graphmath.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/intfgraphics.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/themes.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/freebsd.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/errors.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/sysconst.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/typinfo.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/rtlconsts.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/fpcadds.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl-objpas/strutils.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-base/gettext.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/fgl.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/laz_avl_tree.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/lazfileutils.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/lazutilities.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/lazmethodlist.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/lazutf8classes.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/lazloggerbase.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/laztracer.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/lclstrconsts.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/lazutilsstrconsts.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/lazclasses.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/fpreadbmp.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/fpwritebmp.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/bmpcomn.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/fpreadpng.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/fpwritepng.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/fpreadtiff.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/fpwritetiff.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/fptiffcmn.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/lclversion.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/icnstypes.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/fpimgcmn.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/pngcomn.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/paszlib/zstream.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/paszlib/zbase.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/paszlib/gzio.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/hash/crc.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/paszlib/zdeflate.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/paszlib/zinflate.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/paszlib/trees.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/paszlib/adler.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/paszlib/infblock.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/paszlib/infutil.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/paszlib/infcodes.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/paszlib/inftrees.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/paszlib/inffast.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/lazversion.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/graphics.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/lclintf.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-base/contnrs.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/fpcanvas.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/fpreadpnm.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/fpwritepnm.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/fpreadjpeg.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/fpwritejpeg.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/fpreadgif.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/lresources.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/lclrescache.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wsreferences.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/clipping.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jpeglib.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jdapimin.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jdatasrc.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jdapistd.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jmorecfg.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jdeferr.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jinclude.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jerror.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jmemmgr.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jdmarker.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jdinput.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jcomapi.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jutils.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jmemnobs.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jdmaster.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jdcolor.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jdsample.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jdpostct.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jddctmgr.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jdphuff.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jdhuff.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jdcoefct.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jdmainct.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jquant1.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jquant2.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jdmerge.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jdct.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jidctfst.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jidctint.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jidctflt.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jidctred.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jcapistd.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jcapimin.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jdatadst.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jcparam.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jcinit.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jcmarker.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jcphuff.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jchuff.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jcmaster.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jccolor.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jcsample.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jcprepct.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jcdctmgr.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jccoefct.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jcmainct.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jfdctint.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jfdctfst.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/pasjpeg/jfdctflt.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl-objpas/variants.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/lazconfigstorage.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/dynqueue.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl-objpas/varutils.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/avglvltree.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/lazdbglog.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-base/syncobjs.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/fileutil.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/utf8process.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/lazsysutils.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/maps.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/tmschema.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/masks.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-process/process.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-process/pipes.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl/termio.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtint.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qt5.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/lazstringutils.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/lclmessageglue.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/controls.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/extctrls.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/dialogs.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/stdctrls.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/graphutil.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtproc.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/lclclasses.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/messages.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-base/custapp.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/menus.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/customtimer.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/actnlist.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/clipbrd.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/helpintfs.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/imglist.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/uitypes.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-base/singleinstance.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wslclclasses.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/fpimgcanv.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/fppixlcanv.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/pixtools.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-image/ellipses.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wsimglist.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wsproc.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wsfactory.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/propertystorage.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-base/rttiutils.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wsmenus.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/lazlogger.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/chm/fasthtmlparser.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wscontrols.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wsforms.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/popupnotifier.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/textstrings.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/extendedstrings.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wsstdctrls.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wsextctrls.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/buttons.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/buttonpanel.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/lcltaskdialog.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/imagelistcache.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wsbuttons.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wsdialogs.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/x11/x.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/x11/xlib.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/x11/xkb.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/x11/xkblib.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtcaret.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtthemes.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtwsfactory.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtwidgets.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtobjects.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtsystemtrayicon.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/x11/xi.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/comctrls.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/toolwin.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wscomctrls.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wstoolwin.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtprivate.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/calendar.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/spin.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/grids.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/checklst.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/rubberband.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/pairsplitter.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wscalendar.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wsspin.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-xml/htmldefs.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/maskedit.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/dynamicarray.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/laz2_xmlcfg.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/lcsvutils.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/lazfilecache.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/laz2_dom.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/laz2_xmlread.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/laz2_xmlwrite.o
/home/bartosz/.lazarus/lib/LazUtils/lib/x86_64-freebsd/laz2_xmlutils.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/fcl-base/uriparser.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wsgrids.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wschecklst.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wsdesigner.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wspairsplitter.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtwsbuttons.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtwscalendar.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtwschecklst.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtwscomctrls.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtwscontrols.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtwsdialogs.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtwsextctrls.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtwsforms.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtwsmenus.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtwspairsplitter.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtwsspin.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtwsstdctrls.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtwsgrids.o
/home/bartosz/.lazarus/lib/units/x86_64-freebsd/qt5/qtwsdesigner.o
/usr/local/lib/fpc/3.2.2/units/x86_64-freebsd/rtl-objpas/dateutils.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/extdlgs.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/calcform.o
/home/bartosz/.lazarus/lib/LCLBase/units/x86_64-freebsd/wsextdlgs.o
/usr/home/bartosz/dox/game-project-01/tools/map-editor/lib/x86_64-freebsd/map.o
/usr/home/bartosz/dox/game-project-01/tools/map-editor/lib/x86_64-freebsd/markerdata.o
)
INPUT(
-lQt5Pas
-lX11
-lc
)
INPUT(
/usr/lib/crtendS.o
/usr/lib/crtn.o
)
