package Test2::Tools::PrepareObjects;

use Exporter qw(import);
use Test2::API qw(context);

use header;

our @EXPORT = qw(
	prepare
);

sub prepare ($item)
{
	$item = prepare_identified($item)
		if $item->does('Role::Identified');

	$item = prepare_model($item)
		if $item->isa('Model');

	return $item;
}

sub prepare_identified ($identified)
{
	$identified->{id} = '<autogenerated ULID>';

	return $identified;
}

sub prepare_model ($model)
{
	foreach my $attr ($model->meta->boolean_attrs) {
		my $name = $attr->name;
		$model->{$name} = $model->{$name} ? 1 : 0;
	}

	return $model;
}

