#!/usr/bin/env perl

use v5.36;

use lib 'local/lib/perl5';
use lib 'lib-base';
use lib 'lib';

use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('CLI');

