#!/usr/bin/env perl

use Utils;
use Getopt::Long;
use Server;

use header;

my $processes = 2;

GetOptions(
	'processes|p=i', \$processes,
);

DI->get('log')->filename('logs/server.log');

Utils->bootstrap_mojo;

my $server = Server->new;
$server->start($processes);

