#!/usr/bin/env perl

use strict;
use warnings;
use lib 'lib';

use Utils;
use DI;
use Getopt::Long;

my $processes = 4;

GetOptions(
	'processes|p=i', \$processes,
);

DI->get('log')->filename('logs/server.log');

Utils->bootstrap_lore;
Utils->bootstrap_mojo;

my $server = DI->get('server');
$server->listen($processes);

