#!/usr/bin/env perl

use Utils;
use Getopt::Long;
use Server::Worker;

use header;

my $processes = 2;

GetOptions(
	'processes|p=i', \$processes,
);

DI->get('log')->filename('logs/worker.log');

Utils->bootstrap_mojo;

my $worker = Server::Worker->new;
$worker->start($processes);

