#!/usr/bin/env perl

use strict;
use warnings;
use lib 'lib';

use Utils;
use DI;
use Getopt::Long;

my $processes = 2;

GetOptions(
	'processes|p=i', \$processes,
);

DI->get('log')->filename('logs/worker.log');

Utils->bootstrap_lore;
Utils->bootstrap_mojo;

my $worker = DI->get('worker');
$worker->start($processes);

