#!/usr/bin/env perl

use lib 'local/lib/perl5';
use lib 'lib-base';
use lib 'lib';

use Utils;
use Getopt::Long;
use Server::Worker;

use header;

my $processes = 6;

GetOptions(
	'processes|p=i', \$processes,
);

DI->get('log')->filename('logs/worker.log');

Utils->bootstrap_lore;
Utils->bootstrap_mojo;

my $worker = Server::Worker->new;
$worker->start($processes);

