#!/usr/bin/env perl

use v5.32;
use warnings;
use autodie;

my $dir;
BEGIN {
	use File::Basename;
	$dir = dirname(dirname(__FILE__));
}

use lib "$dir/local/lib/perl5";
use lib "$dir/lib";

use Utils;
use DI;
use Mojo::JSON qw(to_json);

Utils->bootstrap_lore;

my $repo = DI->get('lore_data');
my %lores = $repo->load_all()->%*;

for my $lang (qw(pl)) {
	my @items;
	for my $key (keys %lores) {
		my $item = $lores{$key};
		push @items, {
			LoreId => $item->id,
			LoreName => $item->data->translations->{$lang}{name},
			LoreDescription => $item->data->translations->{$lang}{desc},
		};
	}

	my $struct = {
		Items => \@items
	};

	{
		open my $fh, '>:utf8', "client/data/lore.$lang.json";
		say {$fh} to_json $struct;
	}
}

__END__

=pod

Exports all lores in the system. Used to produce lores file for the client.

