#!/usr/bin/env perl

use Game::LoreLoader;
use Path::Tiny;
use JSON::MaybeXS qw(to_json);

use header;

my ($file) = @ARGV;
die 'you must specify a file path relative to game-data directory'
	unless defined $file;

Game::LoreLoader->load(path($file));

my $repo = DI->get('lore_data_repo');
my %areas = $repo->load_all_named('Game::Lore::Area')->%*;

my @keys = keys %areas;

die 'File contents are too vague - more than one area found'
	unless @keys < 2;
die 'No areas found. Is this file finished?'
	unless @keys > 0;

my @markers;
foreach my $location ($areas{$keys[0]}->children->@*) {
	push @markers, {
		LoreId => $location->id,
		PosX => $location->pos_x // rand,
		PosY => $location->pos_y // rand,
		ConnectedTo => join ';', map { $_->id } $location->connections->@*,
	};
}

my $struct = {
	Markers => \@markers
};

binmode STDOUT, ':utf8';
say to_json $struct;

__END__

=pod

Exports map specified on input. Used in game editor to edit coordinates on a map.

